AWSTemplateFormatVersion: "2010-09-09"

Resources: #リージョン
  DDBT10HT3:
    Type: 'AWS::DynamoDB::Table'
    Properties: #プロパティ
      TableName: Music #テーブルの名前
      AttributeDefinitions: # キースキーマ属性のデータ型
        - AttributeName: Artist #属性の名前 Artist
          AttributeType: S #属性タイプ(String) 
        - AttributeName: SongTitle #属性の名前 SongTitle
          AttributeType: S #属性タイプ(String)
        - AttributeName: AlbumTitle #属性の名前 AlbumTitle
          AttributeType: S #属性タイプ(String)
      KeySchema: #プライマリキーに使用される属性
        - AttributeName: Artist
          KeyType: HASH #ハッシュの定義
        - AttributeName: SongTitle
          KeyType: RANGE #レンジの定義
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      LocalSecondaryIndexes:
        - IndexName: AlbumTitleIndex
          KeySchema:
            - AttributeName: Artist
              KeyType: HASH
            - AttributeName: AlbumTitle
              KeyType: RANGE
          Projection:
            ProjectionType: KEYS_ONLY